name: car_go_pfe_lp_j2ee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: null
  connectivity_plus: null
  firebase_app_check: null
  firebase_auth: null
  firebase_core: null
  firebase_database: ^10.0.0
  firebase_storage: 
  flutter:
    sdk: flutter
  flutter_dotenv: null
  flutter_geofire: null
  flutter_polyline_points: null
  flutter_svg: null
  geolocator: ^12.0.0
  google_maps_flutter: null
  googleapis: null
  googleapis_auth: null
  http: null
  loading_animation_widget: null
  permission_handler: null
  provider: null
  url_launcher: null
  uuid: null
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: null
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

  assets:
    - assets/images/
    - themes/
    - .env
    - service_account_key.json
