name: car_go_pfe_lp_j2ee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: ^5.2.1
  connectivity_plus: ^6.0.5
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_geofire: ^2.0.3
  flutter_polyline_points: ^2.1.0
  flutter_svg: ^2.0.10+1
  geolocator: ^12.0.0
  google_maps_flutter: ^2.9.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  loading_animation_widget: ^1.2.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  url_launcher: ^6.3.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

  assets:
    - assets/images/
    - themes/
    - .env
    - service_account_key.json
